### PR TITLE
Re-Render to support CUDA 11.8

### PR DESCRIPTION
**Pull request by DavidMChan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by DavidMChan** [comment]
This should (probably) resolve #9, however needs review.

**Comment by jakirkham** [comment]
Thanks David! 🙏

Looks pretty good

Do we want to update the GPU arches here?

https://github.com/conda-forge/tsnecuda-feedstock/blob/58be9c9756fa986c1bac1b323bd71dc5f16d7718/recipe/build.sh#L11-L28

Might be worth dropping the old CUDA versions (pre-11.2) and adding the new ones (11.8 and 12.0)

**Comment by DavidMChan** [comment]
Ah, that's a good point - I didn't see this file. Let me take a look.

**Comment by jakirkham** [comment]
If it is helpful, PyTorch has [analogous logic]( https://github.com/conda-forge/pytorch-cpu-feedstock/blob/6773a6361ac4ebba7705c094dff09092bc0c1411/recipe/build.sh#L126-L154 ) that could be adapted here

**Comment by jakirkham** [comment]
Another option might be to just move this to `script_env` in `meta.yaml` and drop the bash logic. We made [similar changes in `nvidia-apex`]( https://github.com/conda-forge/nvidia-apex-feedstock/blob/e90f97b8ce0a313b5bf76ac7b6d4ac414ff6bfff/recipe/meta.yaml#L15-L18 ), which could be a good reference point

**Comment by DavidMChan** [comment]
So I was looking a bit closer at this today, and from what I can tell, we just ignore this code completely in our upstream  CMakeLists (https://github.com/CannyLab/tsne-cuda/blob/2dad49713ba451c0953b646a85ac2567b5d1070e/CMakeLists.txt#L61), since we use the variable CUDA_ARCH, and set it based on the detected CUDAToolkit version. I removed this logic completely, and it seems to still work as expected, but I don't know for sure if these variables have other impacts beyond our upstream package. 

@jakirkham  - thoughts on how to handle this? I think the best thing is just to remove the dead code and handle it upstream, but I'm open to changing the way the upstream works if that's more transparent to conda-forge

**Comment by jakirkham** [comment]
Sounds reasonable to me. Thanks for investigating David! 🙏

Mainly conda-forge packages set it when upstream doesn't have a constraint (or not one we can easily handle on CI here). So packages sometimes need to trim the matrix a bit to keep things manageable. Though no need to do that here if the defaults from upstream cover a good range of architectures and build ok here

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by h-vetinari** [comment]
@DavidMChan, I'm very sorry that I didn't see this PR! 😑 

I rebased it into #12 (without some of the churn-y rerender commits), but I'd very much like to keep you on as a maintainer!

**Comment by DavidMChan** [comment]
Thanks! No worries! Hopefully we can get #12 merged -- I've been pretty behind on issues on the source repo too, so it's all good!

**Pull request closed without merging**
